const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');

const newFallbacks = `const genericFallbacks = [
  "¡Qué temazo acabamos de poner, literal me vuela la cabeza! ¿Quién más está obsesionado?",
  "¡Hola, soy Sofía de Flux Radio! Reportándome en vivo con la música más fresca del momento.",
  "Oye, ¿viste el último trend de TikTok sobre este artista? ¡Qué locura de canción!",
  "¡Qué flow tiene este tema! Quédate conmigo que hoy traemos puros éxitos que la están rompiendo.",
  "¡Increíble la vibra! ¿Sabías que The Weeknd escribió una de sus mejores canciones en menos de 30 minutos? ¡Talento puro!",
  "¡Flux Radio siempre contigo! ¿Saben por qué los DJs aman tanto la lluvia? ¡Porque les encanta ver cómo caen los drops del cielo! Qué tontería.",
  "Oye, ¿has visto el chisme de que Aitana adoptó a otro perrito y le puso de nombre el título de su próxima canción? ¡Adorable, literal!",
  "¡Aquí Sofía de Flux Radio! ¿Qué hace una abeja tocando la trompeta? ¡Hacer zumbido de jazz! Me vuela la cabeza esta tontería.",
  "¡Estás escuchando puros éxitos en Flux Radio! Dicen que Harry Styles tiene un clóset gigante solo para sus trajes con brillo. ¡Qué estilo!",
  "¡Venga, más ritmo! ¿Por qué los músicos siempre sacan buenas notas en los exámenes? ¡Porque estudian en clave de sol! Brutal.",
  "Oye, el último trend de TikTok tiene a todo el mundo recreando videoclips de los noventa. ¡Qué nostalgia tan bonita, de verdad!",
  "¡Sintonizas Flux Radio! ¿Qué le dice un director de orquesta a un músico distraído? ¡Oye, no me des la nota! Me parto de risa.",
  "¡Qué flow tiene este tema! Dicen que Bad Bunny compone descalzo en la playa para conectar con las buenas vibras del Caribe. ¡Qué místico!",
  "¡Flux Radio a tope! ¿Cómo se llama el mejor doctor de la música? ¡El cirujano de los ritmos! Bueno, ese chiste fue penoso, perdón.",
  "Oye, se comenta en redes que Taylor Swift dejó pistas ocultas en el diseño de su nueva línea de camisetas. ¡La agente de la CIA del pop!",
  "¡Estás en Flux Radio! ¿Por qué el disco de vinilo fue a terapia? ¡Porque estaba atrapado en un bucle! De locos, literal.",
  "¡Brutal esta sonido! El otro día vi a Feid en directo y literal el estadio entero vestía de verde. ¡Qué locura de movimiento verde!",
  "¡Flux Radio con Sofía! ¿Cuál es el colmo de un cantante de ópera? ¡Tener una voz tan alta que rompa hasta las reglas del juego!",
  "Oye, ¿has escuchado la última colaboración internacional que acaba de salir? ¡Me tiene bailando por toda la habitación, qué temazo!",
  "¡Sintonizas Flux Radio! ¿Por qué los cantantes de pop aman tanto el espacio exterior? ¡Porque quieren ser estrellas brillantes! Qué bonito.",
  "¡Qué locura chavales! Se rumorea que Rosalía está grabando un tema secreto en Japón con sonidos de videojuegos arcade. ¡Ojalá sea real!",
  "¡Aquí Sofía dándolo todo! ¿Sabéis qué le dijo un bajo a un teclado? ¡Que dejes de ser tan controlador! Qué malo, lo sé.",
  "¡Flux Radio en la casa! ¿Vieron el outfit de Karol G en el último evento? Espectacular, brillando como siempre, la verdadera Bichota.",
  "¡Seguimos con buena música! Dicen que a Bizarrap nunca nadie le ha visto los ojos completos... es como el Batman de la música urbana.",
  "¡Vaya temazo! ¿Saben por qué la guitarra fue al médico? Porque tenía problemas con sus trastes. ¡Madre mía, me supero a mí misma!",
  "Oye, ¿te enteraste de que Billie Eilish grabó las voces de su primer disco sentada en su cama? Literal, de la habitación al mundo entero.",
  "¡Sintonizando Flux Radio! ¿Qué pasa cuando un piano se cae por una mina? ¡Un acorde menor bemol sostenido en do...lor!",
  "¡Increíble la producción de este tema! Cuenta la leyenda que Daft Punk dormía con los cascos puestos. Bueno, es broma, pero molaría.",
  "¡Chavales, atención! El nuevo trend de bailar esta canción en cámara lenta en el supermercado me tiene enganchadísima.",
  "¡Aquí Sofía poniéndole ritmo a tu día! ¿Sabéis cuál es la fruta favorita de Beethoven? ¡La ba-na-na-naaa! Clásico inmortal.",
  "¡Qué buen rollo da esto! Oye, ¿visteis a Rauw Alejandro bailando bajo la lluvia en su último show? Eso es entrega total al público.",
  "¡Flux Radio, la mejor selección! Cuentan por ahí que Quevedo se bebe tres litros de zumo de piña antes de grabar. ¡El secreto del éxito!",
  "¡Tremendo! ¿Sabían que el micrófono más caro del mundo tiene diamantes incrustados? Yo con el de mi cuarto me apaño, ¡y sueno genial!",
  "¡Aquí estamos otra vez! ¿Qué le dice una nota Do a una Re? Eres la siguiente en la escala social. ¡Es que me meo de risa sola!",
  "¡Vaya ritmo lleva esto! Shakira demostró que las caderas no mienten, pero este beat tampoco. ¡De locos, estoy on fire hoy!",
  "¡Flux Radio en directo! ¿Sabéis que Post Malone empezó su carrera subiendo temas a SoundCloud que él mismo mezclaba en su portátil?",
  "¡Madre mía qué canción! Se dice que si escuchas este tema al revés, encuentras la receta perfecta para hacer guacamole. Obvio no, pero imagínate.",
  "¡Qué energía! ¿Cuál es el instrumento más limpio de la orquesta? ¡El bajo! Porque siempre lo están tocando. Perdón, ese fue muy tonto.",
  "¡Sofía en cabina virtual! Chavales, he visto a 20 personas hoy intentar el challenge de esta canción y nadie lo hace bien. ¡A practicar!",
  "¡Brutal la voz de este artista! Dicen que Duki graba sus versos del tirón, sin respirar. ¡El verdadero hombre con pulmones de acero!",
  "¡Flux Radio! ¿Por qué el piano y la guitarra nunca se ponen de acuerdo? Porque siempre están a destiempo en sus opiniones.",
  "¡Súbele al volumen! ¿Sabían que Ed Sheeran casi le regala 'Shape of You' a Rihanna? ¡Menos mal que se la quedó, tremendo exitazo!",
  "¡Qué pasada de canción! Cuentan que Peso Pluma ensaya sus canciones mientras juega al FIFA con los colegas. ¡Puro talento casual!",
  "¡Aquí Sofía! Oye, si la música es el alimento del alma, ¡yo me estoy pegando un banquete increíble hoy con todos vosotros!",
  "¡Flux Radio a tope de decibelios! ¿Sabéis qué hace una corchea triste? Convertirse en una negra. ¡Pobre corchea, necesita un abrazo!",
  "¡Chavales, qué temón! He visto en Twitter que The Eras Tour provocó un pequeño sismo de tanto que saltaba la gente. ¡Literal, tembló la tierra!",
  "¡Seguimos con todo! ¿Sabían que Freddie Mercury tenía cuatro dientes extra y por eso su voz resonaba tan único? ¡Curiosidades que te vuelan la cabeza!",
  "¡Aquí Sofía, tu DJ favorita! ¿Qué le dice un cable de sonido a otro? ¡Oye, a ver si conectamos más a menudo! Vale, prometo mejorar los chistes.",
  "¡De locos este drop! Dicen que Martin Garrix produjo 'Animals' cuando solo tenía 17 añitos. ¡Yo a esa edad apenas sabía hacerme unos cereales!",
  "¡Flux Radio! Oye, ¿visteis el video de Snoop Dogg comentando doma clásica en los Juegos Olímpicos? ¡Ese hombre sirve para absolutamente todo!",
  "¡Qué flow tiene la base! Se comenta que C. Tangana se fue de retiro espiritual y de ahí salió su mejor disco. ¡Habrá que irse al monte a inspirarse!"
];`;

code = code.replace(/const genericFallbacks = \[[^\]]*\];/s, newFallbacks);

fs.writeFileSync('server.ts', code);
