#!/bin/bash
awk '
/async function startServer\(\)/ {
    print "// DJ AI Endpoints"
    print "app.post(\"/api/dj/joke\", async (req, res) => {"
    print "  try {"
    print "    const { voiceName } = req.body;"
    print "    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY, httpOptions: { headers: { \"User-Agent\": \"aistudio-build\" } } });"
    print "    "
    print "    const prompt = `Cuenta un chiste súper corto, gracioso y animado sobre la música, el gimnasio o el día a día. Actúa como si fueras la locutora de FAI-Radio, la mejor radio. Sé muy carismática.`;"
    print "    "
    print "    const response = await ai.models.generateContent({"
    print "      model: \"gemini-3.1-flash-tts-preview\","
    print "      contents: [{ parts: [{ text: prompt }] }],"
    print "      config: {"
    print "        responseModalities: [\"AUDIO\"],"
    print "        speechConfig: {"
    print "          voiceConfig: {"
    print "            prebuiltVoiceConfig: { voiceName: voiceName || \"Kore\" }"
    print "          }"
    print "        }"
    print "      }"
    print "    });"
    print "    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;"
    print "    if (!base64Audio) {"
    print "      return res.status(500).json({ error: \"No audio generated\" });"
    print "    }"
    print "    res.json({ audio: base64Audio });"
    print "  } catch (err) {"
    print "    console.error(\"DJ AI Joke Error:\", err);"
    print "    res.status(500).json({ error: \"Failed to generate DJ joke\" });"
    print "  }"
    print "});"
    print ""
    print "app.post(\"/api/dj/test-voice\", async (req, res) => {"
    print "  try {"
    print "    const { voiceName } = req.body;"
    print "    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY, httpOptions: { headers: { \"User-Agent\": \"aistudio-build\" } } });"
    print "    "
    print "    const prompt = `Di con entusiasmo: Hola, soy tu locutora de FAI-Radio probando la voz ${voiceName}. ¿Qué te parece?`;"
    print "    "
    print "    const response = await ai.models.generateContent({"
    print "      model: \"gemini-3.1-flash-tts-preview\","
    print "      contents: [{ parts: [{ text: prompt }] }],"
    print "      config: {"
    print "        responseModalities: [\"AUDIO\"],"
    print "        speechConfig: {"
    print "          voiceConfig: {"
    print "            prebuiltVoiceConfig: { voiceName: voiceName || \"Kore\" }"
    print "          }"
    print "        }"
    print "      }"
    print "    });"
    print "    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;"
    print "    if (!base64Audio) {"
    print "      return res.status(500).json({ error: \"No audio generated\" });"
    print "    }"
    print "    res.json({ audio: base64Audio });"
    print "  } catch (err) {"
    print "    console.error(\"DJ AI Test Voice Error:\", err);"
    print "    res.status(500).json({ error: \"Failed to generate test voice\" });"
    print "  }"
    print "});"
    print ""
}
{ print }
' server.ts > server_new.ts
mv server_new.ts server.ts
